name: Test

on:
  workflow_dispatch:
  push:

jobs:
  release:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Apt
        run: sudo apt install -y dnsutils socat openjdk-21-jdk-headless openjdk-21-jre-headless

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Build
        run: go build

      - name: Test
        run: go test

      - name: Install
        run: go install

      - name: End To End
        run: |
          sudo aa-unload
          sudo systemctl stop apparmor
          go run ./testing/run-tests
