name: Test

on:
  workflow_dispatch:
  push:

jobs:
  release:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Apt
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: dia doxygen doxygen-doc doxygen-gui doxygen-latex graphviz mscgen
          version: 1.0

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build
        run: go build

      - name: Test
        run: go test

      - name: Install
        run: |
          go install
          sudo setcap 'cap_net_admin=ep cap_sys_admin=ep cap_dac_override=ep' $(which httptap)

      - name: End To End
        run: go run ./testing/run-tests
