name: Test

on:
  workflow_dispatch:
  push:

jobs:
  release:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Env
        run: env

      - name: Apt
        run: sudo apt install -y dnsutils socat openjdk-21-jdk-headless openjdk-21-jre-headless

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Build
        run: go build

      - name: Test
        run: go test

      - name: Install
        run: |
          go install
          sudo setcap 'cap_net_admin=ep cap_sys_admin=ep cap_dac_override=ep' $(which httptap)

      - name: End To End
        run: go run ./testing/run-tests
